version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.3
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  git-version: {}

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

commands:
  check-calculation-results:    
    parameters:
      output_folder:
        type: string
        default: "outputs"
        description: "The directory where file with outputs will be created."
      output_file:
        type: string
        default: ""
        description: "The name of the file with calculation results."
      expected_next_version_prod:
        type: string
        default: ""
        description: "Expected next prod version."
      expected_next_version_rc:
        type: string
        default: ""
        description: "Expected next rc version."
      expected_next_version_beta:
        type: string
        default: ""
        description: "Expected next beta version."
      expected_next_version_alpha:
        type: string
        default: ""
        description: "Expected next alpha version."
    steps:
      - attach_workspace:
          at: /home/circleci/git-version/<< parameters.output_folder >>
      
      - run:
          name: Check results
          command: |            
            source /home/circleci/git-version/<< parameters.output_folder >>/<< parameters.output_file >>

            echo "NEXT_VERSION_PROD=${NEXT_VERSION_PROD}"
            if [[ "${NEXT_VERSION_PROD}" != "<< parameters.expected_next_version_prod >>" ]]; then
              echo "Expected << parameters.expected_next_version_prod >> but got ${NEXT_VERSION_PROD}"
              exit 1
            fi

            echo "NEXT_VERSION_RC=${NEXT_VERSION_RC}"
            if [[ "${NEXT_VERSION_RC}" != "<< parameters.expected_next_version_rc >>" ]]; then
              echo "Expected << parameters.expected_next_version_rc >> but got ${NEXT_VERSION_RC}"
              exit 1
            fi

            echo "NEXT_VERSION_BETA=${NEXT_VERSION_BETA}"
            if [[ "${NEXT_VERSION_BETA}" != "<< parameters.expected_next_version_beta >>" ]]; then
              echo "Expected << parameters.expected_next_version_beta >> but got ${NEXT_VERSION_BETA}"
              exit 1
            fi

            echo "NEXT_VERSION_ALPHA=${NEXT_VERSION_ALPHA}"
            if [[ "${NEXT_VERSION_ALPHA}" != "<< parameters.expected_next_version_alpha >>" ]]; then
              echo "Expected << parameters.expected_next_version_alpha >> but got ${NEXT_VERSION_ALPHA}"
              exit 1
            fi

jobs:
  test-calculation:
    working_directory: /home/circleci/git-version
    docker:
      - image: cimg/base:current
    steps:
      # Test: alpha only
      - git-version/calculate:
          debug: "true"
          output_file: test1
          tags: "v1.11.0-alpha.1 v1.11.0-alpha.2"

      - check-calculation-results:
          output_file: test1
          expected_next_version_alpha: "v1.11.0-alpha.3"
          expected_next_version_beta: "v1.11.0-beta.1"
          expected_next_version_rc: "v1.11.0-rc.1"

      # Test: beta only
      - git-version/calculate:
          debug: "true"
          output_file: test2
          tags: "v1.11.0-beta.1 v1.11.0-beta.2"

      - check-calculation-results:
          output_file: test2
          expected_next_version_alpha: "v1.11.0-alpha.1"
          expected_next_version_beta: "v1.11.0-beta.3"
          expected_next_version_rc: "v1.11.0-rc.1"

      # Test: rc only
      - git-version/calculate:
          debug: "true"
          output_file: test3
          tags: "v1.11.0-rc.1"

      - check-calculation-results:
          output_file: test3
          expected_next_version_alpha: "v1.11.0-alpha.1"
          expected_next_version_beta: "v1.11.0-beta.1"
          expected_next_version_rc: "v1.11.0-rc.2"

      # Test: prod only #1
      - git-version/calculate:
          debug: "true"
          output_file: test4
          tags: "v1.11.0 v1.11.0-alpha.2 v1.11.0-beta.1"

      - check-calculation-results:
          output_file: test4
          expected_next_version_prod: "v1.11.0"

      # Test: prod only #2
      - git-version/calculate:
          debug: "true"
          output_file: test4_1
          tags: "v1.11.0 v1.10.111 v9.123.2222"

      - check-calculation-results:
          output_file: test4_1
          expected_next_version_prod: "v9.123.2222"


      # Test: alpha & beta & rc & prod & different x.x.x part
      - git-version/calculate:
          debug: "true"
          output_file: test5
          tags: "v1.11.0-alpha.1 v1.11.0-beta.2 v1.11.0-rc.1 v1.11.0 v2.0.1-alpha.1"

      - check-calculation-results:
          output_file: test5
          expected_next_version_alpha: "v2.0.1-alpha.2"
          expected_next_version_beta: "v2.0.1-beta.1"
          expected_next_version_rc: "v2.0.1-rc.1"

      # Test: alpha & beta & rc & prod & different x.x.x part
      - git-version/calculate:
          debug: "true"
          output_file: test5_1
          tags: "v1.11.0-alpha.1 v1.11.0-beta.2 v1.11.0-rc.9 v1.11.0 v2.0.1-alpha.9"

      - check-calculation-results:
          output_file: test5_1
          expected_next_version_alpha: "v2.0.1-alpha.10"
          expected_next_version_beta: "v2.0.1-beta.1"
          expected_next_version_rc: "v2.0.1-rc.1"

      # Test: valid & invalid tags #1
      - git-version/calculate:
          debug: "true"
          output_file: test6
          tags: "v1.11.0-alpha.1 v1.11.0-beta.2 2.0.1-alpha.9 3.0.1.1 2-3-4-5"

      - check-calculation-results:
          output_file: test6
          expected_next_version_alpha: "v1.11.0-alpha.2"
          expected_next_version_beta: "v1.11.0-beta.3"
          expected_next_version_rc: "v1.11.0-rc.1"

      # Test: valid & invalid tags + extra spaces
      - git-version/calculate:
          debug: "true"
          output_file: test7
          tags: "  0.18.3-alpha 1.0.0-alpha.10 v0.1.0 v0.10.0 v0.11.0 v0.11.1 v0.11.2 v0.12.0 v0.13.0 v0.14.0 v0.14.1 v0.15.0 v0.15.1 v0.16.0 v0.16.1 v0.16.2 v0.16.2-beta.0 v0.17.0 v0.17.1 v0.17.1-CP420.1 v0.18.0 v0.18.1 v0.18.2-beta.0 v0.18.2-beta.1 v0.18.2-beta.10 v0.18.2-beta.12 v0.18.2-beta.13 v0.18.2-beta.14 v0.18.2-beta.15 v0.18.2-beta.16 v0.18.2-beta.17 v0.18.2-beta.18 v0.18.2-beta.2 v0.18.2-beta.3 v0.18.2-beta.4 v0.18.2-beta.5 v0.18.2-beta.6 v0.18.2-beta.7 v0.18.2-beta.8 v0.18.2-beta.9 v0.18.3-alpha v0.18.3-alpha.1 v0.2.0 v0.3.0 v0.4.0 v0.4.1 v0.5.0 v0.5.1 v0.6.0 v0.7.0 v0.8.0 v0.9.0 v1.0.0 v1.0.0-alpha.1 v1.0.0-alpha.10 v1.0.0-alpha.11 v1.0.0-alpha.12 v1.0.0-alpha.13 v1.0.0-alpha.14 v1.0.0-alpha.15 v1.0.0-alpha.16 v1.0.0-alpha.17 v1.0.0-alpha.18 v1.0.0-alpha.19 v1.0.0-alpha.2 v1.0.0-alpha.20 v1.0.0-alpha.21 v1.0.0-alpha.22 v1.0.0-alpha.23 v1.0.0-alpha.24 v1.0.0-alpha.25 v1.0.0-alpha.26 v1.0.0-alpha.27 v1.0.0-alpha.28 v1.0.0-alpha.29 v1.0.0-alpha.3 v1.0.0-alpha.30 v1.0.0-alpha.31 v1.0.0-alpha.32 v1.0.0-alpha.33 v1.0.0-alpha.4 v1.0.0-alpha.5 v1.0.0-alpha.6 v1.0.0-alpha.7 v1.0.0-alpha.8 v1.0.0-alpha.9 v1.0.0-beta.1 v1.0.0-beta.10 v1.0.0-beta.2 v1.0.0-beta.3 v1.0.0-beta.4 v1.0.0-beta.5 v1.0.0-beta.6 v1.0.0-beta.7 v1.0.0-beta.8 v1.0.0-beta.9 v1.0.1-alpha.1 v1.0.1-alpha.2 v1.0.1-alpha.3 v1.0.1-alpha.4 v1.0.1-alpha.5 v1.0.1-alpha.6 v1.0.1-alpha.7 v1.0.2-alpha.1 v1.0.2-alpha.2 v1.0.3-alpha.1 v1.0.3-alpha.2 v1.0.4-alpha.1 v1.0.4-alpha.2 v1.0.5-alpha.1 v1.0.5-alpha.2 v1.0.5-alpha.3 v1.0.6-alpha.1 v1.0.6-alpha.2 v1.0.6-alpha.3 v1.0.7-alpha.1  v1.0.7-alpha.2 v1.0.8-alpha.1   v1.0.8-alpha.2   "

      - check-calculation-results:
          output_file: test7
          expected_next_version_alpha: "v1.0.8-alpha.3"
          expected_next_version_beta: "v1.0.8-beta.1"
          expected_next_version_rc: "v1.0.8-rc.1"

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
      - test-calculation:
          filters: *filters
      - git-version/use_git_tags_for_calculation:
          debug: "true"
          output_file: test8
          filters: *filters
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: mt-lab/git-version
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - test-calculation
          context: orb-publishing
          filters: *release-filters
